name: Python CI

# Trigger the workflow on push or pull request events on the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository's code.
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the Python environment.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install the dependencies from requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests using pytest.
      - name: Run Tests
        run: pytest
